name: Eclobby
version: '${version}'
main: fr.efreicraft.eclobby.Main
api-version: 1.19
authors: [ DocSystem ]
description: Efrei Craft Lobby Plugin
website: https://github.com/efrei-craft/eclobby

commands:
  lobby:
    description: Vous téléporte au spawn
    usage: /lobby
    aliases: [hub, spawn]
    permission: eclobby.lobby
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.
  join:
    description: Vous téléporte sur un serveur
    usage: /join <serveur>
    permission: eclobby.join
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.

permissions:
  eclobby.lobby:
    description: Permet d'utiliser le /lobby
  eclobby.join:
    description: Permet d'utiliser le /join
  eclobby.fly:
    description: Permet de voler
  eclobby.menu:
